#%RAML 1.0
title: product-api
baseUri: http://locahost:8081/products
/products:
  get:
    description: To get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productId" : "121",
                "productName": "ABC",
                "productProvider": "Udemy",
                "productDescription": "This is a test Product"
              }